### ISSUE TITLE
Need setters to do validation when setting message fields

### ISSUE THREAD

**Issue by maximecb** [Shopify/protoboeuf#68]
There's an issue where some fields can't accept some values. For example, an unsigned integer can't be set to a negative value.

Right now, the code to encode unsigned integers will just go into an infinite loop when trying to encode if we set an unsigned integer field to `-1` for example. This is clearly not desirable or expected.

IMO, these kinds of validation errors should be caught as early as possible, ideally when field values are set, rather than when messages are encoded, and so we need some validation logic inside setter methods for message fields.

This is technically to protect protoboeuf users from themselves, so maybe not as high priority as other things, but it needs to happen eventually, and I think catching negative values or values out of range is probably the most important kind of validation that we need to do.

**Comment by TobiasBales** [comment]
The wrong type supplied could probably be mitigated by using sorbet (I just opened a PR for generated sorbet types from the definition).

I would see about adding range validation to the encoder if I am getting the gist of this conversation right next
